name: facebook_sdk
description: A new flutter plugin project.
version: 0.0.2
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: it.wher.facebook_sdk
    pluginClass: FacebookSdkPlugin